class Feedback < ActiveRecord::Base

  FEEDBACK_TYPE_BUG = 0
  FEEDBACK_TYPE_ENHANCEMENT = 1
  FEEDBACK_TYPE_INAPPROPRIATE = 2
  FEEDBACK_TYPE_INACCURATE = 3
  
  FEEDBACK_TYPE_DESCS = [
    [FEEDBACK_TYPE_BUG, 'Bug'],
    [FEEDBACK_TYPE_ENHANCEMENT, 'Enhancement'],
    [FEEDBACK_TYPE_INAPPROPRIATE, 'Inappropriate'],
    [FEEDBACK_TYPE_INACCURATE, 'Inaccurate'],
  ]
  FEEDBACK_TYPE_DESC_MAP = FEEDBACK_TYPE_DESCS.to_hash
  
  FEEDBACK_STAGE_NEW = 0
  FEEDBACK_STAGE_ASSIGNED = 1
  FEEDBACK_STAGE_HANDLED = 2
  
  FEEDBACK_STAGE_DESCS = [
    [FEEDBACK_STAGE_NEW, 'New'],
    [FEEDBACK_STAGE_ASSIGNED, 'Assigned'],
    [FEEDBACK_STAGE_HANDLED, 'Handled'],
  ]
  FEEDBACK_STAGE_DESC_MAP = FEEDBACK_STAGE_DESCS.to_hash
  
end
