development:
  adapter: mysql
  database: planner_scrape
  host: localhost
  username: root
  password: 

test:
  adapter: mysql
  database: planner_scrape
  host: localhost
  username: root
  password: 

production:
  adapter: mysql
  database: planner_scrape
  host: skobee.kicks-ass.net
  username: scraper
  password: gJYH1DUT
